import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { description, caseId, originalDescription, clarifications } = await req.json();
    
    console.log('Generating sketch for case:', caseId);
    console.log('Description:', description);

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Build the prompt for forensic sketch generation
    const forensicPrompt = `Create a highly detailed, realistic forensic sketch of a person based on this description: ${description}. 
    
The sketch should be:
- In black and white or grayscale, like a professional police forensic sketch
- Frontal view of the face
- Highly detailed and realistic
- Professional quality, as if drawn by a forensic artist
- Clear facial features matching the description
- No background, just the face portrait`;

    console.log('Calling Lovable AI for image generation...');

    // Call Lovable AI to generate the image
    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: forensicPrompt
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Lovable AI error:', response.status, errorText);
      throw new Error(`Failed to generate sketch: ${errorText}`);
    }

    const data = await response.json();
    console.log('Received response from Lovable AI');

    // Extract the generated image
    const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    if (!imageUrl) {
      throw new Error('No image generated in response');
    }

    // Convert base64 to blob
    const base64Data = imageUrl.split(',')[1];
    const imageBlob = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    // Upload to Supabase Storage
    const fileName = `sketch-${caseId}-${Date.now()}.png`;
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('case-evidence')
      .upload(fileName, imageBlob, {
        contentType: 'image/png',
        upsert: false
      });

    if (uploadError) {
      console.error('Storage upload error:', uploadError);
      throw new Error(`Failed to upload sketch: ${uploadError.message}`);
    }

    console.log('Sketch uploaded to storage:', fileName);

    // Store the file path instead of a public URL since bucket is private
    const filePath = fileName;
    console.log('File path:', filePath);

    // Save to media table with metadata (store file path, not URL)
    // Note: embedding will be generated separately via generate-sketch-embedding function
    const { data: mediaData, error: mediaError } = await supabase
      .from('media')
      .insert({
        case_id: caseId,
        url: filePath,
        type: 'sketch',
        embedding: null, // Will be generated by image analysis
        meta: {
          description: description,
          originalDescription: originalDescription,
          clarifications: clarifications,
          generatedAt: new Date().toISOString()
        }
      })
      .select()
      .single();

    if (mediaError) {
      console.error('Database insert error:', mediaError);
      throw new Error(`Failed to save sketch metadata: ${mediaError.message}`);
    }

    console.log('Sketch saved to database with ID:', mediaData.id);

    // Generate embedding from the actual image using vision analysis
    console.log('Generating image-based embedding...');
    let embeddingSuccess = false;
    try {
      const embeddingResult = await supabase.functions.invoke('generate-sketch-embedding', {
        body: {
          media_id: mediaData.id
        }
      });

      if (embeddingResult.error) {
        console.error('Error generating image embedding:', embeddingResult.error);
        throw embeddingResult.error;
      } else {
        console.log('Image embedding generated successfully:', embeddingResult.data);
        embeddingSuccess = true;
      }
    } catch (embeddingError) {
      console.error('Failed to generate image embedding:', embeddingError);
      // Return error since embedding is required for matching
      return new Response(
        JSON.stringify({
          success: false,
          error: 'Failed to generate embedding for sketch'
        }),
        {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Generate a signed URL for the response (valid for 1 hour)
    const { data: signedUrlData } = await supabase.storage
      .from('case-evidence')
      .createSignedUrl(filePath, 3600);

    const signedUrl = signedUrlData?.signedUrl || filePath;

    // Automatically trigger suspect matching after embedding is ready
    let matchResults = null;
    if (embeddingSuccess) {
      try {
        console.log('Triggering automatic suspect matching...');
        const matchResponse = await supabase.functions.invoke('find-suspect-matches', {
          body: {
            caseId: caseId,
            sketchId: mediaData.id,
            threshold: 0.7
          }
        });

        if (matchResponse.error) {
          console.error('Error triggering automatic matching:', matchResponse.error);
        } else {
          console.log('Automatic matching completed:', matchResponse.data);
          matchResults = matchResponse.data;
        }
      } catch (matchError) {
        console.error('Failed to trigger automatic matching:', matchError);
        // Don't fail the whole request if matching fails
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        sketchUrl: signedUrl,
        mediaId: mediaData.id,
        embeddingGenerated: embeddingSuccess,
        matches: matchResults
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error) {
    console.error('Error in generate-sketch function:', error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : 'Unknown error occurred'
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
