// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inamnmxmxayyojuajddm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluYW1ubXhteGF5eW9qdWFqZGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODU4NjIsImV4cCI6MjA3MjY2MTg2Mn0.fxpDOkbOBKvwWFkg0reNBJk4evTxWycLdOqBSv1beec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});